import csv
import json
import math

import networkx as nx
import pandas as pd
import colorcet


# Colors used for different graph Modularity Classes
COLORS = colorcet.glasbey_dark
OUTPUT_JSON = "public/pytexas.json"
OUTPUT_ENTITY_CLUSTER_TSV = "entity_clusters.tsv"

NODE_SCALING = 2
EDGE_SCALING = 2.5

# Fallback for missing numeric fields in GraphML (invalid JSON if NaN slips through)
NUMERIC_FALLBACK = 100.0

# GraphML file generated by Gephi
INPUT_GRAPHML = "entity_graph_layout.graphml"

# Keys = Gephi Modularity Class in GraphML, not the size-sorted ids in entity_clusters.tsv.
CLUSTERS = [
    {"key": "0", "clusterLabel": "Systems & containers"},
    {"key": "1", "clusterLabel": "Tooling & packaging"},
    {"key": "2", "clusterLabel": "Other languages & frameworks"},
    {"key": "3", "clusterLabel": "API & data"},
    {"key": "4", "clusterLabel": "Python apps & testing"},
    {"key": "5", "clusterLabel": "Cloud & platforms"},
    {"key": "6", "clusterLabel": "Notebooks & hardware"},
    {"key": "other", "clusterLabel": "Other"},
]

# Optional: human-readable label -> node_ids (must match GraphML node_id / entity string).
# Listed nodes are moved into dedicated clusters; counts then participate in size-ordered keys.
OVERRIDES: dict[str, list[str]] = {
    "AI & LLMs": [
        "ai",
        "openai",
        "llm",
        "langchain",
        "gpt",
    ],
    "Zen": [
        "pythonic",
        "the zen of python",
    ],
}

KNOWN_CLUSTER_KEYS = {c["key"] for c in CLUSTERS}

BOUND = 1500
BOUNDING_BOX = {"x": [-BOUND, BOUND], "y": [-BOUND, BOUND]}

LABEL_THRESHOLD = 12


def _no_nan_float(obj):
    """Recursively replace float NaN so JSON is valid (and strict serializers accept it)."""
    if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
        return NUMERIC_FALLBACK
    if isinstance(obj, dict):
        return {k: _no_nan_float(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_no_nan_float(v) for v in obj]
    return obj


if __name__ == "__main__":

    G = nx.read_graphml(path=INPUT_GRAPHML)

    _nodes_df = pd.DataFrame.from_dict(dict(G.nodes(data=True)), orient="index").reset_index().rename(
        columns={"index": "node_id"}
    )
    _edges_df = nx.to_pandas_edgelist(G=G)

    node_cols = ["node_id", "x", "y", "label", "size", "Modularity Class"]
    if "n_talks" in _nodes_df.columns:
        node_cols.append("n_talks")
    nodes_df = _nodes_df[node_cols].copy()
    edges_df = _edges_df[["source", "target", "weight"]].copy()

    def _cluster_key(mod_class) -> str:
        if pd.isna(mod_class):
            return "other"
        k = str(mod_class).strip()
        return k if k in KNOWN_CLUSTER_KEYS else "other"

    nodes_df["cluster"] = nodes_df["Modularity Class"].map(_cluster_key)
    nodes_df = nodes_df.drop(columns=["Modularity Class"])

    override_label_by_syn: dict[str, str] = {}
    if OVERRIDES:
        ov_i = 0
        for display_label, entity_list in OVERRIDES.items():
            if not entity_list:
                continue
            syn = f"ov_{ov_i}"
            override_label_by_syn[syn] = display_label
            ov_i += 1
            for ent in entity_list:
                m = nodes_df["node_id"] == ent
                if m.any():
                    nodes_df.loc[m, "cluster"] = syn

    # New keys "0".."n-1": 0 = largest community, 1 = second, ... (by node count; ties → key name)
    _counts = nodes_df["cluster"].value_counts()
    _old_keys_by_size = sorted(_counts.index.tolist(), key=lambda k: (-_counts[k], str(k)))
    _old_to_new_cluster = {old: str(i) for i, old in enumerate(_old_keys_by_size)}
    nodes_df["cluster"] = nodes_df["cluster"].map(_old_to_new_cluster)

    _label_by_modularity_key = {c["key"]: c["clusterLabel"] for c in CLUSTERS}

    def _cluster_label_for_old_key(old_k: str) -> str:
        if old_k in override_label_by_syn:
            return override_label_by_syn[old_k]
        return _label_by_modularity_key[old_k]

    clusters_for_json = [
        {
            "key": str(i),
            "clusterLabel": _cluster_label_for_old_key(old_k),
            "color": COLORS[i],
        }
        for i, old_k in enumerate(_old_keys_by_size)
    ]

    if "n_talks" in nodes_df.columns:
        n_talks_series = pd.to_numeric(nodes_df["n_talks"], errors="coerce").fillna(0).astype(int)
    else:
        n_talks_series = pd.Series(0, index=nodes_df.index, dtype=int)

    entity_cluster_rows = (
        pd.DataFrame(
            {
                "entity": nodes_df["node_id"],
                "cluster": nodes_df["cluster"],
                "n_talks": n_talks_series,
                "_cluster_order": nodes_df["cluster"].astype(int),
            }
        )
        .sort_values(
            by=["_cluster_order", "n_talks", "entity"],
            ascending=[True, False, True],
        )
        .drop(columns=["_cluster_order", "n_talks"])
    )

    with open(OUTPUT_ENTITY_CLUSTER_TSV, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, delimiter="\t", lineterminator="\n")
        w.writerow(["entity", "cluster"])
        for row in entity_cluster_rows.itertuples(index=False):
            w.writerow([row.entity, row.cluster])

    # Integer key per node: same order as rows (includes isolates; matches edge source/target ids)
    node_id_to_key = {nid: i for i, nid in enumerate(nodes_df["node_id"])}
    nodes_df["key"] = nodes_df["node_id"].map(node_id_to_key)

    for col in ("x", "y", "size"):
        nodes_df[col] = pd.to_numeric(nodes_df[col], errors="coerce").fillna(NUMERIC_FALLBACK)
    nodes_df["size"] = nodes_df["size"] / NODE_SCALING

    nodes = nodes_df.drop(columns=["node_id"]).to_dict(orient="records")

    def _edge_weight(w) -> float:
        v = pd.to_numeric(w, errors="coerce")
        return float(NUMERIC_FALLBACK if pd.isna(v) else v)

    edges = [
        [
            node_id_to_key[e["source"]],
            node_id_to_key[e["target"]],
            _edge_weight(e["weight"]) / EDGE_SCALING,
        ]
        for e in edges_df.to_dict(orient="records")
    ]

    data = {
        "nodes": nodes,
        "edges": edges,
        "clusters": clusters_for_json,
        "bbox": BOUNDING_BOX,
        "labelThreshold": LABEL_THRESHOLD,
    }

    data = _no_nan_float(data)

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(obj=data, fp=f, separators=(",", ":"), allow_nan=False)
